title: Vista IoT Documentation
description: Official documentation for Vista IoT Gateway Platform - comprehensive guides, API references, and setup instructions for industrial IoT solutions.
baseurl: "/Docs"
url: "https://vista-iot.github.io"

# Theme
theme: minima

# Navigation
header_pages:
  - getting-started.md
  - architecture.md
  - hardware.md
  - diagrams.md
  - api-reference.md
  - tutorials.md
  - contributing.md

# Social links
minima:
  social_links:
    github: Vista-IOT

# Plugins
plugins:
  - jekyll-feed
  - jekyll-sitemap

# Markdown processor
markdown: kramdown
highlighter: rouge

# Mermaid support
mermaid:
  # Version of mermaid library
  # Pick an available version from https://cdn.jsdelivr.net/npm/mermaid/
  version: "10.6.1"

# Enable Mermaid
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge

# Exclude files
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
  - vendor/

